"""Add countdownresult model

Revision ID: 29095d5f2d8f
Revises: 4f87800bba37
Create Date: 2021-03-19 19:13:19.820614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29095d5f2d8f'
down_revision = '4f87800bba37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countdown_result',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('finish_date', sa.DateTime(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('countdown_result')
    # ### end Alembic commands ###
