"""Add db structure

Revision ID: 4f87800bba37
Revises: 
Create Date: 2021-03-14 16:13:35.812299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f87800bba37'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('registered_on', sa.DateTime(), nullable=False),
    sa.Column('last_success_login', sa.DateTime(), nullable=True),
    sa.Column('last_failure_login', sa.DateTime(), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.Column('password_reset_token', sa.String(length=255), nullable=True),
    sa.Column('password_reset_hash', sa.String(length=255), nullable=True),
    sa.Column('password_reset_sent_at', sa.DateTime(), nullable=True),
    sa.Column('activation_token', sa.String(length=255), nullable=True),
    sa.Column('activation_hash', sa.String(length=255), nullable=True),
    sa.Column('activation_sent_at', sa.DateTime(), nullable=True),
    sa.Column('activated', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('cite')
    # ### end Alembic commands ###
